### ISSUE TITLE
Ingen fails to compile

### ISSUE THREAD

**Issue by therealkitman** [drobilla/ingen#1]
Hi,
I seem to be the first issue here :) 

Trying to build on opensuse 42.2 -I puled this latest commit of ingen - https://github.com/drobilla/ingen/commit/29ad2127d35e347decd92545c4884d5a41f286d0 - from the site after having built all the precursor libs (suil, sord etc) from the latest commits and placing in my special audio folder.

As a precaution I set the PKG_CONGIF_PATH as well.

`export PKG_CONFIG_PATH="$HOME/AudioSoftware/builds/lib/pkgconfig:$HOME/AudioSoftware/builds/lib64/pkgconfig:/usr/lib/pkgconfig:/usr/lib64/pkgconfig:/usr/share/pgkconfig"
`
The configure works ok.
```
chris@linux-c4x2:~/AudioSoftware/git/ingen> ./waf configure LDFLAGS="-L$HOME/AudioSoftware/builds/lib -L$HOME/AudioSoftware/builds/lib64" CFLAGS="-I$HOME/AudioSoftware/builds/include -I/usr/include" --prefix=~/AudioSoftware/builds --docs --lv2dir=~/.lv2
Setting top to                           : /home/chris/AudioSoftware/git/ingen 
Setting out to                           : /home/chris/AudioSoftware/git/ingen/build 
Checking for 'g++' (C++ compiler)             : /usr/bin/g++-6 
Checking for program 'python'                 : /usr/bin/python 
Checking for program 'doxygen'                : /usr/bin/doxygen 
Checking for program 'tar'                    : /bin/tar 
Checking for flag '-std=c++14'                : yes 
Checking for library gcov                     : yes 
Checking for header boost/format.hpp          : yes 
Checking for header boost/intrusive/slist.hpp : yes 
Checking for header boost/intrusive_ptr.hpp   : yes 
Checking for header boost/optional.hpp        : yes 
Checking for header boost/variant.hpp         : yes 
Checking for thread_local keyword             : yes 
Checking for program 'pkg-config'             : /usr/bin/pkg-config 
Checking for 'lv2'                            : yes 
Checking for 'glibmm-2.4'                     : yes 
Checking for 'gthread-2.0'                    : yes 
Checking for 'lilv-0'                         : yes 
Checking for 'suil-0'                         : yes 
Checking for 'sratom-0'                       : yes 
Checking for 'raul'                           : yes 
Checking for 'serd-0'                         : yes 
Checking for 'sord-0'                         : yes 
Checking for 'portaudio-2.0'                  : yes 
Checking for posix_memalign                   : yes 
Checking for isatty                           : yes 
Checking for vasprintf                        : yes 
Checking for library dl                       : yes 
Checking for socket                           : yes 
Checking for python version >= 2.4.0          : 2.7.13 
Checking for 'jack'                           : yes 
Checking for jack_set_property                : yes 
Checking for jack_port_rename                 : no 
Checking for compiler flags ['-pthread']      : yes 
Checking for linker flags ['-pthread']        : yes 
Checking for linker flags ['-lpthread']       : yes 
Checking for 'gtkmm-2.4'                      : yes 
Checking for 'gtkmm-2.4'                      : yes 
Checking for 'ganv-1'                         : yes 
Checking for 'webkit-1.0'                     : yes 
 
  Install prefix                              : /home/chris/AudioSoftware/builds 
  Debuggable build                            : no 
  Build documentation                         : yes 
  GUI                                         : yes 
  HTML plugin documentation support           : yes 
  PortAudio driver                            : yes 
  Jack driver                                 : yes 
  Jack session support                        : yes 
  Jack metadata support                       : yes 
  LV2 plugin driver                           : yes 
  LV2 bundle                                  : ~/.lv2/ingen.lv2 
  LV2 plugin support                          : yes 
  Socket interface                            : yes 

'configure' finished successfully (3.161s)
```
But when I compile, it keeps failing. Something about AtomWriter??? I have pasted the full screen output here  [https://pastebin.com/LHRVSkug](url)

Is there a clue here as to what is going wrong for me?

Thanks,
Chris.

**Comment by drobilla** [comment]
Weird.  You must have an old boost or something.  Should be fixed by https://github.com/drobilla/ingen/commit/9dfdf5d1d36f90aaa9a9d0d165d62b744dde837b

**Comment by therealkitman** [comment]
Thank you. Which minimum version of boost is needed? I have the boost 
source for v1.66 ready to compile as my system version is 1.61

**Comment by therealkitman** [comment]
I got the new patch ok -

```
chris@linux-c4x2:~/AudioSoftware/git/ingen> git pull
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/drobilla/ingen
   29ad2127..9dfdf5d1  master     -> origin/master
Updating 29ad2127..9dfdf5d1
Fast-forward
 ingen/AtomWriter.hpp | 2 ++
 1 file changed, 2 insertions(+)
```
After re-running the configure step I still get compiler errors. See [errors](https://pastebin.com/MbhBcmum)

**Comment by drobilla** [comment]
GCC version?  This is probably fixable (sorry, I don't test ingen on anything older than stretch), but it probably won't build with 4.6

**Comment by therealkitman** [comment]
I used both the system default version of 4.8 and version 6 via the CC and CXX flags

```
export CC=/usr/bin/gcc-6
export CXX=/usr/bin/g++-6

```

**Comment by therealkitman** [comment]
I don't know if this helps you. I extracted the code from the output of the failed build and ran it separately.

In this case I tried to build `ingen/build/src/server/DuplexPort.cpp.1.o` which failed. It had errors reported at the bottom.

Full output is at [here](https://pastebin.com/quKn5A9C)

**Comment by therealkitman** [comment]
I did some more playing today with the output code as listed above. I find if I change the 2nd -std (the one after the -fPIC flag) from -stdc++11 to -stdc++14 then the script runs and compiles.

`/usr/bin/g++-6 -I/home/chris/AudioSoftware/git/ingen -DNDEBUG -std=c++14 -fshow-column -pthread -fPIC -std=c++11 -Isrc/server...`

I use the CC and CXX vars as mentioned and I have even edited the gcc and g++ symlinks in /usr/bin to point to the gcc-6 and g++-6 binaries but with no luck. Obviously g++-6 is being called but how is the -stdc++11 flag getting set instead of -stdc--14? [Output](https://pastebin.com/N8MWztWJ)

**Comment by drd-ableton** [comment]
It should only be using `-std=c++14` if your compiler supports it, which it does.  I have no idea where that `-std=c++11` is coming from unless it's in your `CXXFLAGS` or your tree is somehow dirty?

**Comment by drobilla** [comment]
It should only be using -std=c++14 if your compiler supports it, which it does. I have no idea where that -std=c++11 is coming from unless it's in your CXXFLAGS or your tree is somehow dirty?

**Comment by therealkitman** [comment]
I deleted the entire ingen folder and did a new git clone from master. Still failed to build.

Under the build/c4che is file _cache.py. It had 3 CXXFLAGS set to c++11. I edited them to c++14 and now ingen compiles and runs. 

Any clue as you why those 3 flags would be set like this? The GLIBMM, GTKMM packages are from the opensuse system repos.

```
CXXFLAGS = ['-I/home/chris/AudioSoftware/git/ingen', '-DNDEBUG', '-std=c++14', '-fshow-column']
CXXFLAGS_GANV = ['-pthread']
CXXFLAGS_GLIBMM = ['-std=c++14']   <-----------------was set to -std=c++11
CXXFLAGS_GTHREAD = ['-pthread', '-pthread']
CXXFLAGS_GTKMM = ['-std=c++14', '-pthread'] <-----------------was set to -std=c++11
CXXFLAGS_MACBUNDLE = ['-fPIC']
CXXFLAGS_NEW_GTKMM = ['-std=c++14', '-pthread'] <-----------------was set to -std=c++11
CXXFLAGS_PORTAUDIO = ['-pthread']
CXXFLAGS_WEBKIT = ['-pthread']
CXXFLAGS_cxxshlib = ['-fPIC']
```

![screenshot_20180110_085557](https://user-images.githubusercontent.com/14888092/34750939-b88a9464-f5e4-11e7-8bf9-49488541b1b5.png)
![screenshot_20180110_085614](https://user-images.githubusercontent.com/14888092/34750945-beddee38-f5e4-11e7-9d23-faa02b3eb2d6.png)

**Comment by drd-ableton** [comment]
Oh, so it's from the glibmm pkg-config, and apparently the latest doesn't take priority.  Well, that's fun...

**Comment by therealkitman** [comment]
I'm a complete novice when it comes to compiling but do I assume you 
mean that the glibmm libraries in the system repo were compiled with a 
version of GCC older that v6 eg v4.8?

**Comment by drobilla** [comment]
Not really, it's because the pkg-config file for these libraries (probably in /usr/lib/pkgconfig) explicitly includes that flag.

In any case, your issue should be fixed as of 34fb90e18a20cfc780cdef660e6da391baf1bcde

**Comment by therealkitman** [comment]
Did a checkout of https://github.com/drobilla/ingen/commit/af3e1e78558c7b0917c6bf2f838bc90452ab514e which came out shortly after the commit mentioned above and compilation is ok now.

Thank you very much.
